#!/usr/bin/env python
# coding: utf-8

"""
NLP-Powered Urdu Articles Search Engine

Implements three information retrieval scoring methods for Urdu text:
  1. TF-IDF (Term Frequency - Inverse Document Frequency)
  2. Okapi BM25
  3. Dirichlet Smoothing (Language Model)

Requires index files (term_info.txt, term_index.txt) and a Documents/
directory containing Urdu HTML articles, plus an 'Urdu stopwords.txt' file.
"""

import os
import re

from bs4 import BeautifulSoup
import numpy as np
from nltk.tokenize import word_tokenize

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Directory containing the Urdu HTML article files
DOCUMENTS_DIR = os.environ.get("DOCUMENTS_DIR", "Documents")

# Path to index files generated by the indexer
TERM_INFO_FILE = os.environ.get("TERM_INFO_FILE", "term_info.txt")
TERM_INDEX_FILE = os.environ.get("TERM_INDEX_FILE", "term_index.txt")
STOPWORDS_FILE = os.environ.get("STOPWORDS_FILE", "Urdu stopwords.txt")

# Output files for scoring results
TFIDF_OUTPUT = "tf_idf_score.txt"
BM25_OUTPUT = "okapi_bm25_score.txt"
DIRICHLET_OUTPUT = "dirichlet_smoothing_score.txt"

# Compile regex pattern to remove non-alphanumeric characters
patterns = re.compile(r'[^\w\s]+')

# ---------------------------------------------------------------------------
# Build lookup dictionaries from index files
# ---------------------------------------------------------------------------

def load_term_ids(term_info_path):
    """Build a dict mapping term -> term_id (1-indexed) from term_info.txt.

    Each line in term_info.txt is assumed to be:
        term\toffset\t...\tdf
    """
    term_ids = {}
    with open(term_info_path, encoding='utf-8') as f:
        for line_no, line in enumerate(f, start=1):
            parts = line.strip().split('\t')
            if parts and parts[0]:
                term_ids[parts[0]] = line_no
    return term_ids


def load_doc_ids(documents_dir):
    """Build a dict mapping filename -> doc_id (1-indexed) for every file in
    the documents directory."""
    doc_ids = {}
    for idx, filename in enumerate(sorted(os.listdir(documents_dir)), start=1):
        doc_ids[filename] = idx
    return doc_ids


def load_stopwords(stopwords_path):
    """Return a list of stopwords from the given file."""
    with open(stopwords_path, encoding='utf-8') as f:
        return f.read().split('\n')


# Initialize global lookup tables
term_IDS = load_term_ids(TERM_INFO_FILE) if os.path.exists(TERM_INFO_FILE) else {}
doc_IDS = load_doc_ids(DOCUMENTS_DIR) if os.path.isdir(DOCUMENTS_DIR) else {}

# ---------------------------------------------------------------------------
# Query list for testing the search engine
# ---------------------------------------------------------------------------

query_list = [
    'مجرم کو پھانسی دے دی گئی',
    'احتجاجی دھرنے, جلوس اور ریلیاں',
    'انسداد تمباکو نوشی کے اقدامات اور آگاہی',
    'وکلاء کی ہڑتال اور ریلیاں',
    'خفیہ ایجنسیاں اور جاسوس',
    'احتساب عدالت کے مقدمات',
    'بچوں کے خلاف تشدد اور اغوا',
    'عورتوں پر ظلم و تشدد , قتل اور اغوا',
    'انسانوں کی اسمگلنگ اور انسداد انسانی سمگلنگ کے اقدامات',
    'مزدور طبقے کی خوشحالی کے اقدامات',
]

# ---------------------------------------------------------------------------
# Core retrieval helpers
# ---------------------------------------------------------------------------

def process_query(query):
    """Process a query string and return (sorted list of matching doc IDs,
    list of keyword tokens)."""
    stop_words = load_stopwords(STOPWORDS_FILE)

    query = re.sub(patterns, '', query)
    tokens = word_tokenize(query)
    keywords = [word for word in tokens if word not in stop_words]

    document_set = set()

    for word in keywords:
        if word not in term_IDS:
            continue
        term_id = term_IDS[word]
        with open(TERM_INFO_FILE) as term_info_file:
            lines = term_info_file.read().split('\n')
            lines.pop()
            term_info = lines[term_id - 1].split('\t')
            with open(TERM_INDEX_FILE) as term_index_file:
                term_index_file.seek(int(term_info[1]), 0)
                index_line = term_index_file.readline().split('\t')
                index_line.pop()
                postings = [list(map(int, posting.split(':')))
                            for posting in index_line[1:]]

                doc_id_sum = 0
                for doc_id, freq in postings:
                    doc_id_sum += doc_id
                    document_set.add(doc_id_sum)

    document_list = sorted(list(document_set))
    return document_list, keywords


def calculate_tf(term, document):
    """Calculate term frequency of *term* in *document* (a filename)."""
    document_id = doc_IDS[document]
    term_id = term_IDS[term]

    with open(TERM_INFO_FILE) as term_info_file:
        lines = term_info_file.read().split('\n')
        lines.pop()
        term_info = lines[term_id - 1].split('\t')

        with open(TERM_INDEX_FILE) as term_index_file:
            term_index_file.seek(int(term_info[1]), 0)
            index_line = term_index_file.readline().split('\t')
            index_line.pop()
            postings = [list(map(int, posting.split(':')))
                        for posting in index_line[1:]]

            doc_id_sum = 0
            for i, (doc_id, freq) in enumerate(postings):
                doc_id_sum += doc_id
                if doc_id_sum == document_id:
                    postings = postings[i:]
                    break

            term_positions = [postings[0][1]]
            cumulative_freq = postings[0][1]
            for doc_id, freq in postings[1:]:
                cumulative_freq += freq
                if doc_id == 0:
                    term_positions.append(cumulative_freq)
                else:
                    break

    return len(term_positions)


def calculate_idf(term):
    """Calculate inverse document frequency for *term*."""
    term_id = term_IDS[term]

    with open(TERM_INFO_FILE) as term_info_file:
        lines = term_info_file.read().split('\n')
        lines.pop()
        term_info = lines[term_id - 1].split('\t')

    return np.log10(len(doc_IDS) / int(term_info[3]))


# ---------------------------------------------------------------------------
# 1. TF-IDF Scoring
# ---------------------------------------------------------------------------

def run_tfidf(query_list):
    """Compute TF-IDF scores for each query and write results to file."""
    # Clear previous output
    open(TFIDF_OUTPUT, 'w').close()

    for query_id, query_text in enumerate(query_list, start=1):
        documents, keywords = process_query(query_text)
        document_scores = {}

        for document in documents:
            filename = [name for name in doc_IDS if doc_IDS[name] == document][0]
            tf_query_product = 0

            for keyword in keywords:
                tf_idf = ((1 + np.log10(calculate_tf(keyword, filename)))
                          * calculate_idf(keyword))
                query_tf = 1 + np.log10(keywords.count(keyword))
                tf_query_product += tf_idf * query_tf

            document_scores[filename] = tf_query_product

        sorted_scores = sorted(document_scores.items(),
                               key=lambda item: item[1], reverse=True)

        with open(TFIDF_OUTPUT, 'a') as out:
            for rank, (doc_name, score) in enumerate(sorted_scores, start=1):
                out.write(f"{query_id}  {doc_name}  {rank}  {score}  run 1\n")


# ---------------------------------------------------------------------------
# 2. Okapi BM25 Scoring
# ---------------------------------------------------------------------------

def calculate_p1(term):
    """BM25 IDF component: log10((N + 0.5) / (df + 0.5))."""
    term_id = term_IDS[term]

    with open(TERM_INFO_FILE) as term_info_file:
        lines = term_info_file.read().split('\n')
        lines.pop()
        term_info = lines[term_id - 1].split('\t')

    return np.log10((len(doc_IDS) + 0.5) / (int(term_info[3]) + 0.5))


def compute_avg_doc_length():
    """Compute the average document length (in words, excluding stopwords)
    across all documents in DOCUMENTS_DIR."""
    stop_words = load_stopwords(STOPWORDS_FILE)
    total_length = 0

    for doc_filename in sorted(os.listdir(DOCUMENTS_DIR)):
        with open(os.path.join(DOCUMENTS_DIR, doc_filename),
                  encoding='utf-8') as f:
            content = f.read()
        soup = BeautifulSoup(content, "html.parser")
        text = re.sub(patterns, '', soup.get_text())
        tokens = word_tokenize(text)
        words = [t for t in tokens if t not in stop_words]
        total_length += len(words)

    return total_length / len(doc_IDS) if doc_IDS else 0


def calculate_K(doc_filename, average_length):
    """BM25 document-length normalisation factor K."""
    stop_words = load_stopwords(STOPWORDS_FILE)
    k1 = 1.2
    b = 0.75

    with open(os.path.join(DOCUMENTS_DIR, doc_filename),
              encoding='utf-8') as f:
        content = f.read()
    soup = BeautifulSoup(content, "html.parser")
    text = re.sub(patterns, '', soup.get_text())
    tokens = word_tokenize(text)
    words = [t for t in tokens if t not in stop_words]

    return k1 * ((1 - b) + b * (len(words) / average_length))


def calculate_okapi_bm25(keywords, document_list, average_length):
    """Return a dict {filename: bm25_score} for the given keyword list and
    candidate document IDs."""
    k2 = 10
    document_scores = {}

    for document in document_list:
        filename = [name for name in doc_IDS if doc_IDS[name] == document][0]
        bm25_score = 0

        for keyword in keywords:
            tf = calculate_tf(keyword, filename)
            K = calculate_K(filename, average_length)
            qtf = 1 + np.log10(keywords.count(keyword))

            bm25_score += (calculate_p1(keyword)
                           * (((1 + 1.2) * tf) / (K + tf))
                           * (((1 + k2) * qtf) / (k2 + qtf)))

        document_scores[filename] = bm25_score

    return document_scores


def run_bm25(query_list):
    """Compute Okapi BM25 scores for each query and write results to file."""
    open(BM25_OUTPUT, 'w').close()
    average_length = compute_avg_doc_length()

    for query_id, query_text in enumerate(query_list, start=1):
        documents, keywords = process_query(query_text)
        bm25_scores = calculate_okapi_bm25(keywords, documents, average_length)
        sorted_scores = sorted(bm25_scores.items(),
                               key=lambda item: item[1], reverse=True)

        with open(BM25_OUTPUT, 'a') as out:
            for rank, (doc_name, score) in enumerate(sorted_scores, start=1):
                out.write(f"{query_id}  {doc_name}  {rank}  {score}  run 1\n")


# ---------------------------------------------------------------------------
# 3. Dirichlet Smoothing (Language Model) Scoring
# ---------------------------------------------------------------------------

def build_background_model():
    """Build a background word list from all documents for Dirichlet
    smoothing and return (background_words, total_word_count)."""
    stop_words = load_stopwords(STOPWORDS_FILE)
    background_words = []
    total_word_count = 0

    for doc_filename in sorted(os.listdir(DOCUMENTS_DIR)):
        with open(os.path.join(DOCUMENTS_DIR, doc_filename),
                  encoding='utf-8') as f:
            content = f.read()
        soup = BeautifulSoup(content, "html.parser")
        text = re.sub(patterns, '', soup.get_text())
        tokens = word_tokenize(text)
        words = [t for t in tokens if t not in stop_words]
        total_word_count += len(words)
        background_words.extend(words)

    return background_words, total_word_count


def run_dirichlet(query_list):
    """Compute Dirichlet smoothing scores for each query and write results
    to file."""
    open(DIRICHLET_OUTPUT, 'w').close()
    stop_words = load_stopwords(STOPWORDS_FILE)
    background_words, total_word_count = build_background_model()

    # mu = average document length
    mu = total_word_count / len(doc_IDS) if doc_IDS else 1

    for query_id, query_text in enumerate(query_list, start=1):
        documents, keywords = process_query(query_text)
        dirichlet_scores = {}

        for document in documents:
            filename = [name for name in doc_IDS
                        if doc_IDS[name] == document][0]

            with open(os.path.join(DOCUMENTS_DIR, filename),
                      encoding='utf-8') as f:
                content = f.read()
            soup = BeautifulSoup(content, "html.parser")
            text = re.sub(patterns, '', soup.get_text())
            tokens = word_tokenize(text)
            words = [t for t in tokens if t not in stop_words]

            document_score = 1
            lam = len(words) / (len(words) + mu)

            for keyword in keywords:
                bg_prob = (background_words.count(keyword)
                           / len(background_words)) if background_words else 0
                doc_prob = (words.count(keyword)
                            / len(words)) if words else 0
                document_score *= lam * doc_prob + (1 - lam) * bg_prob

            dirichlet_scores[filename] = document_score

        sorted_scores = sorted(dirichlet_scores.items(),
                                key=lambda item: item[1], reverse=True)

        with open(DIRICHLET_OUTPUT, 'a') as out:
            for rank, (doc_name, score) in enumerate(sorted_scores, start=1):
                out.write(
                    f"{query_id}  {doc_name}  {rank}  {score}  run 1\n")


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    if not doc_IDS:
        print(f"[WARNING] No documents found in '{DOCUMENTS_DIR}/'.")
        print("  Make sure the Documents directory exists and contains "
              "the Urdu HTML article files.")
    if not term_IDS:
        print(f"[WARNING] Could not load term index from '{TERM_INFO_FILE}'.")
        print("  Make sure term_info.txt and term_index.txt are present.")

    if doc_IDS and term_IDS:
        print("Running TF-IDF scoring...")
        run_tfidf(query_list)
        print(f"  -> Results written to {TFIDF_OUTPUT}")

        print("Running Okapi BM25 scoring...")
        run_bm25(query_list)
        print(f"  -> Results written to {BM25_OUTPUT}")

        print("Running Dirichlet Smoothing scoring...")
        run_dirichlet(query_list)
        print(f"  -> Results written to {DIRICHLET_OUTPUT}")

        print("Done.")
    else:
        print("Aborting: required data files are missing.")
